//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_order
    {
        public int order_detail_id { get; set; }
        public int order_id { get; set; }
        public int book_id { get; set; }
        public Nullable<int> status { get; set; }
        public int book_status { get; set; }
        public Nullable<int> book_deposit { get; set; }
        public Nullable<int> order_qty { get; set; }
    
        public virtual order order { get; set; }
    }
}
