//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detail_order
    {
        public int order_detail_id { get; set; }

        [Display(Name = "Mã Đơn Mượn")]
        public int order_id { get; set; }

        [Display(Name = "Tên Sách")]
        public int book_id { get; set; }

        [Display(Name = "Trạng Thái")]
        public Nullable<int> status { get; set; }

        [Display(Name = "Tình trạng sách")]
        public int book_status { get; set; }

        [Display(Name = "Giá Mượn")]
        public Nullable<int> book_price { get; set; }
    
        public virtual book book { get; set; }
        public virtual order order { get; set; }
    }
}
