//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public const int BOOK_RETURN_FALSE = 0;
        public const int BOOK_RETURN_TRUE = 1;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.detail_order = new HashSet<detail_order>();
        }
    
        public int order_id { get; set; }
        public Nullable<System.DateTime> order_from { get; set; }
        public Nullable<System.DateTime> order_to { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int user_id { get; set; }
        public Nullable<int> order_pay { get; set; }
        public Nullable<int> order_deposit { get; set; }
        public Nullable<int> order_forfeit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_order> detail_order { get; set; }
        public virtual user user { get; set; }
    }
}
